### ISSUE TITLE
Proxy's Staff Of Power crashes on server.

### ISSUE THREAD

**Issue by Darkhax** [tophatcats-mods/creepy-creepers#3]
```
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.func_213324_a(DFZ)Lnet/minecraft/util/math/RayTraceResult;
	at com.mcmoddev.creepycreepers.common.misc.ItemProxysStaffOfPower.func_77659_a(ItemProxysStaffOfPower.java:43) ~[?:1.14.4-1.0.0.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:273) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:865) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:32) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}
```

**Comment by ProxyNeko** [comment]
Tis a tool I used to test it’s not meant to be in the final release will remove it in the next build, only crashes on a dedicated server

**Comment by ProxyNeko** [comment]
Forgot to close this ages ago...

**Comment by Darkhax** [comment]
lol
